name: 🐍 Generate Snake Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *" # every day at midnight UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: udayan-majumder
          outputs: |
            ./output/snake.svg

      - name: Push to output branch
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add output/snake.svg
          git commit -m "Generate new snake graph 🐍" || echo "No changes to commit"
          git push
